---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 24.04.2023 21:32
---

local class = require("libs/30log")

local HPBar = class("Gui.HPBar", {
    total = 0,
    current = 0,

    width = 0,
    s = 2
})

-- Static function

function HPBar.load()
    HPBar.texture = love.graphics.newImage("assets/gui/HpBars2.png")
    HPBar.texture:setWrap("repeat", "clampzero")
end

function HPBar:init(width, total, s)
    self.quad = love.graphics.newQuad(0, 0, 3*width, 7, HPBar.texture:getDimensions())
    self.width = width
    self.total = total
    self.s = s or 2
end

function HPBar:setHP(hp)
    self.current = hp
    local ratio = 1 - self.current / self.total

    if self.empty_quad then self.empty_quad:release() end
    self.empty_quad = love.graphics.newQuad(-3 * ratio * self.width, 7, 3 * ratio * self.width, 7, HPBar.texture:getDimensions())
end

function HPBar:draw(x, y)
    local ratio = self.current / self.total

    love.graphics.draw(HPBar.texture, self.quad, x, y, 0, self.s, self.s)
    love.graphics.draw(HPBar.texture, self.empty_quad, x + 6 * ratio * self.width, y, 0, self.s, self.s)

end

return HPBar