---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 16.10.2022 12:20
---

local Camera = require("libs/Camera")
local ForestLevel = require("levels/forest")

function love.load()
    camera = Camera()
    camera:setDeadzone(camera.w/2 - 80, 0, 80, camera.h)
    camera.scale = 1.5

    love.physics.setMeter(64)
    ForestLevel.load()
end

function love.update(dt)
    ForestLevel.update(dt)
end

function love.draw()
    local dt = love.timer.getDelta()
    ForestLevel.draw(dt)
end

function love.keypressed(key, scancode, is_repeat)
    if ForestLevel.keypressed then
        ForestLevel.keypressed(key, scancode, is_repeat)
    end
end

function love.keyreleased(key, scancode)
    if ForestLevel.keyreleased then
        ForestLevel.keyreleased(key, scancode)
    end
end