---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 16.10.2022 12:20
---

local Camera = require("libs/Camera")
local ForestLevel = require("levels/forest")
local MainMenu = require("levels/main_menu")

function CHANGE_LEVEL(level)
    CURRENT_LEVEL = level
    CURRENT_LEVEL.load()
end

function love.load()
    camera = Camera()
    camera:setDeadzone(camera.w/2 - 80, 0, 80, camera.h)
    camera.scale = 1.5

    love.physics.setMeter(64)

    CURRENT_LEVEL = ForestLevel;
    CURRENT_LEVEL.load()
end

function love.update(dt)
    CURRENT_LEVEL.update(dt)
end

function love.draw()
    local dt = love.timer.getDelta()
    CURRENT_LEVEL.draw(dt)
end

function love.keypressed(key, scancode, is_repeat)
    if CURRENT_LEVEL.keypressed then
        CURRENT_LEVEL.keypressed(key, scancode, is_repeat)
    end
end

function love.keyreleased(key, scancode)
    if CURRENT_LEVEL.keyreleased then
        CURRENT_LEVEL.keyreleased(key, scancode)
    end
end