---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 16.10.2022 17:40
---

local class = require("libs/30log")

local ForestLevel = class("ForestLevel")

function ForestLevel:init()

end

