---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 19.07.2023 23:03
---

local Stack = require("utility/stack")
local class = require("libs/30log")

local Behavior = class("Behavior")

function Behavior:onAdd(entity)
    if entity[entity.behavior] == nil then
        pdump(entity)
        error("Entity has no component with name of behavior", 2)
    end

    fill_table(entity[entity.behavior], {
        messages = Stack()
    })
end

function Behavior:process(entity, dt)
    local behavior = entity[entity.behavior]

    while behavior.messages:size() ~= 0 do
        local message = behavior.messages:pop()
        local command = message[1]

        if self[command] then
            self[command](self, entity, dt, message[2])
        end
    end
end

return Behavior