---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 19.07.2023 23:03
---

local Stack = require("utility/stack")

--- Disclaimer - there is a Behavior-Component and Behavior-System.
--- The class presented here via Lua-Language-Server is the former, but the code after is for the latter  
---@class Behavior
---@field messages Stack

local Behavior = CLASS("Behavior")

function Behavior:onAdd(entity)
    if entity[entity.behavior] == nil then
        pdump(entity)
        error("Entity has no component with name of behavior", 2)
    end

    entity[entity.behavior].messages = entity[entity.behavior].messages or Stack()
end

function Behavior:process(entity, dt)
    local behavior = entity[entity.behavior]

    while behavior.messages:size() ~= 0 do
        local message = behavior.messages:pop()
        local command = message[1]

        if self[command] then
            self[command](self, entity, dt, message[2])
        end
    end
end

return Behavior