---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 08.02.2023 18:31
---

local Vector2 = require("utility/vector")[1]
local Stack = require("utility/stack")
local dump = require("utility/dump")

local Sprite = require("src/graphics/Sprite")[1]
local CategoryManager = require("src/CategoryManager")

local tiny = require("libs/tiny")
local Behavior = require("src/behavior/Behavior")

local BulletBehavior = tiny.processingSystem(Behavior:extend("BulletBehavior"))
BulletBehavior.filter = tiny.requireAll("bullet", "body")

function BulletBehavior:_explosion(entity)
    local p_world = entity.body:getWorld()
    local world = self.world
    local x, y = entity.body:getPosition()

    local animation = GraphicsLoader.animations.explosion:clone()
    local explosion = {
        sprite = animation
    }
    explosion.body = love.physics.newBody(p_world, x, y, "static")
    animation.animations.default[1].onLoop = function(anim, loops)
        explosion.body:destroy()
        tiny.removeEntity(world, explosion)
    end

    world:addEntity(explosion)
    return explosion
end

function BulletBehavior:contact(entity, dt, data)
    local other = data[2]
    if other.caller ~= nil then return end

    if other.entity.health then
        other.entity.health.change = -10
    end

    local world = self.world
    self:_explosion(entity)
    tiny.removeEntity(world, entity)
end

function BulletBehavior:onRemove(entity)
    entity.body:destroy()
end


return BulletBehavior