---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 08.02.2023 18:31
---

local Vector2 = require("utility/vector")[1]
local Stack = require("utility/stack")
local dump = require("utility/dump")

local Sprite = require("src/Sprite")[1]
local CategoryManager = require("src/CategoryManager")

local tiny = require("libs/tiny")

local BulletBehavior = tiny.processingSystem()
BulletBehavior.filter = tiny.requireAll("bullet", "body")

function BulletBehavior:onAdd(entity)
    if entity.bullet.messages then
        return
    end
    entity.bullet.messages = Stack()
end

function BulletBehavior:process(entity, dt)
    while entity.bullet.messages:size() ~= 0 do
        local message = entity.bullet.messages:pop()
        local command = message[1]

        if self[command] then
            self[command](self, entity, dt, message[2])
        end
    end
end

function BulletBehavior:contact(entity, dt, other)
    if other.health then
        other.health.change = -10
    end

    local world = self.world
    tiny.removeEntity(world, entity)
    entity.body:destroy()
end


return BulletBehavior