---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 07.07.2023 10:46
---
local Vector2 = require("utility/vector")[1]
local Stack = require("utility/stack")
local dump = require("utility/dump")
local Torus = require("utility/torus")
local Timer = require("utility/timer")

local Sprite = require("src/graphics/Sprite")[1]
local CategoryManager = require("src/CategoryManager")
local Effects = require("src/graphics/Effects")

local tiny = require("libs/tiny")


local TruckBehavior = tiny.processingSystem()
TruckBehavior.filter = tiny.requireAll("truck", "body", "sprite")

function TruckBehavior:onAdd(entity)
    fill_table(entity.truck, {
        messages = Stack(),
        stack = Stack(),

        -- Default team setting - enemy
        team = CategoryManager.categories.enemy
    })

    CategoryManager.setObject(entity.fixture, entity.truck.team)
end

function TruckBehavior:process(entity, dt)
    local truck = entity.truck

    -- Command logic
    while truck.messages:size() ~= 0 do
        local message = truck.messages:pop()
        local command = message[1]

        if self[command] then
            self[command](self, entity, dt, message[2])
        end
        ::continue::
    end
end

--- Move block
---@param vel - Vector2
function TruckBehavior:move(entity, dt, vel)
    local v = Vector2(vel)

    local velocity = v * 100
    if v:mag() > 1 then
        velocity = velocity / v:mag()
    end

    --entity.truck.is_moving = true
    entity.sprite:set("move")
    entity.body:setLinearVelocity(velocity:x(), velocity:y())
end

function TruckBehavior:stop(entity, dt)
    --entity.truck.is_moving = false
    entity.sprite:set("idle")
    entity.body:setLinearVelocity(0, 0)
end

function TruckBehavior:hurt(entity, dt)
    if entity.sprite == nil then
        entity.sprite = Effects.hurt()
    end
end

function TruckBehavior:die(entity, dt)
    local world = self.world
    tiny.removeEntity(world, entity)
end

function TruckBehavior:onRemove(entity)
    entity.body:destroy()
end

return TruckBehavior