---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 12.11.2022 2:12
---

local ignore_keys = {
    "__tostring", "__instances", "__call", "__subclasses", "__index", "init", "includes", "create", "mixins", "class",
    "extend", "with", "without", "subclasses", "subclassOf", "instances", "instanceOf", "cast", "new", "classOf",
}

function table.contains(table, element)
    for _, value in pairs(table) do
        if value == element then
            return true
        end
    end
    return false
end

---@param o - Object to dump
---@param n - nesting parameter
---@param i - how many tabs
local function dump(o, n, i)
    i = i or 0
    local offset = string.rep("  ", i+1)

    if type(o) == 'table' then
        local s = '{\n'
        for k,v in pairs(o) do
            if (table.contains(ignore_keys, k)) then
                goto continue
            end

            if type(k) == 'string' then k = '"'..k..'"' end
            if type(k) == 'table' then k = "/?table?/" end
            local temp
            if (i < n) then
                temp = dump(v, n, i+1)
            else
                temp = tostring(v)
            end
            s =  s .. offset .. '['..k..'] = ' .. temp .. ',\n'
            ::continue::
        end
        return s ..  string.rep("  ", i) .. '} '
    else
        return tostring(o)
    end
end

return dump