---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 31.03.2023 18:07
---

require("libs/strong")

--- Recursively calls table by string with '.' separator
--- Example, table looks like this: 
--- t = { a: { b: 10 }, c: 5 }
--- Then rcall would do:
--- rcall(t, "a.b") -- result: 10
--- @param obj table
--- @param path string
function rcall(obj, path)
    local split = path / "."
    local output = obj
    for i, v in ipairs(split) do
        output = output[v]
    end
    return output
end


--- Recursively creates key path in table by path given with '.' separator.
--- Fills with empty table at the end
--- Returns the table for convinience
--- Example: 
--- path = "i.love.cheese"
--- t = {}
--- rcreate(t, path) --- t.i.love.cheese = {}
---@param obj table
---@param path string
---@return table
function rcreate(obj, path)
    local split = path / "."
    local operate = obj
    for i, v in ipairs(split) do
        operate[v] = {}
        operate = operate[v]
    end
    return operate
end


function rcopy(table, s)
    if type(table) ~= 'table' then return table end

    local seen = s or {}
    if seen[table] then return seen[table] end

    local res = {}
    seen[table] = res
    for k, v in pairs(table) do
        res[k] = rcopy(v, seen) -- there was copy(k, s) for key
    end
    return res
end