---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 31.03.2023 18:07
---

require("libs/strong")

--- @param obj table
--- @param path string
function rcall(obj, path)
    local split = path / "."
    local output = obj
    for i, v in ipairs(split) do
        output = output[v]
    end
    return output
end


function rcreate(obj, path)
    local split = path / "."
    operate = obj
    for i, v in ipairs(split) do
        operate[v] = {}
        operate = operate[v]
    end
    return operate
end


function rcopy(table, s)
    if type(table) ~= 'table' then return table end

    local seen = s or {}
    if seen[table] then return seen[table] end

    local res = {}
    seen[table] = res
    for k, v in pairs(table) do
        res[k] = rcopy(v, seen) -- there was copy(k, s) for key
    end
    return res
end