---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 17.03.2023 23:42
---

local function fill_table(table, defaults)
    for k, v in pairs(defaults) do
        if type(table[k]) == "table" and type(v) == "table" then
            fill_table(table[k], v)
        end

        if table[k] ~= nil then
            goto continue
        end

        table[k] = v
        ::continue::
    end
end

return fill_table