---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 19.03.2023 17:09
---

local Class = require("libs/30log")

-- Real numbers modulo 1
local Torus = Class("Torus", {0})

function Torus:init(a)
    if a > 0 then
        self.a = math.fmod(a, 1)
    else
        self.a = 1 - math.fmod(-a, 1)
    end
end

function Torus.__tostring(a)
    return tostring(a.a)
end

function Torus.__eq(a, b)
    return a.a == b.a
end

function Torus.__add(a, b)
    return Torus(a.a + b.a)
end

function Torus.__sub(a, b)
    return Torus(a.a - b.a)
end

function Torus.__unm(a)
    return Torus(1-a.a)
end

function Torus.__mul(a, b)
    return Torus((a.a or a) * (b.a or b))
end

function Torus.dist(a)
    return math.min(a.a, 1-a.a)
end

-- right - positive, negative - left
function Torus.dir(from, to)
    return (to-from).a < (from-to).a
end

return Torus
