---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 16.10.2022 12:42
---

local Vector = {0,0}

function Vector:new(o)
    out = o or {}
    setmetatable(out, self)
    self.__index = self
    return out
end

function Vector.__add(a, b)
    out = Vector:new()
    out[1] = a[1] + b[1]
    out[2] = a[2] + b[2]
    return out;
end

function Vector.__unm(a)
    out = Vector:new()
    out[1] = -a[1]
    out[2] = -a[2]
    return out;
end

function Vector.__sub(a, b)
    return a + (-b)
end

-- S - scalar, V - vector
local function MulSV(a, b)
    if type(a) == "table" then
        return b * a
    end
    out = Vector:new()
    out[1] = a * b[1]
    out[2] = a * b[2]
    return out
end

local function MulVV(a, b)
    out = Vector:new()
    out[1] = a[1] * b[1]
    out[2] = a[2] * b[2]
    return out
end

function Vector.__mul(a, b)
    if (type(a) == "table") and (type(b) == "table") then
        return MulVV(a, b)
    else
        return MulSV(a, b)
    end
end

function Vector:x()
    return self[1]
end

function Vector:y()
    return self[2]
end

return Vector