---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 13.11.2022 1:13
---

local class = require("libs/30log")

local Scene = class("Scene", {
    load = function()  end,
    update = function(dt)  end,
    draw = function(dt)  end,
    keypressed = function(key, scancode, is_repeat) end,
    keyreleased = function(key, scancode) end,
    mousepressed = function(x, y, button, istouch, presses) end,
    mousereleased = function(x, y, button, istouch, presses) end,
    mousemoved = function(x, y, dx, dy, istouch)  end,
    resize = function(w, h)  end
})

return Scene