---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 04.01.2023 21:44
---

--- player NOT collides with player_bullets and player


local CATEGORIES = {
    player = 1,
    player_bullets = 2,

    enemy = 3,
    enemy_bullets = 4,

    neutral = 5,
    neutral_bullets = 6,

    bulletproof = 7
}

local CategoryManager = {};
CategoryManager.categories = CATEGORIES

function CategoryManager.setBullet(fixture, type)
    if
        type ~= CATEGORIES.player_bullets and
        type ~= CATEGORIES.enemy_bullets and
        type ~= CATEGORIES.neutral_bullets
        then
        error("Wrong type of category")
        return
    end
    fixture:setCategory(type)
    fixture:setMask(type, type - 1, CATEGORIES.bulletproof)
end

function CategoryManager.setObject(fixture, type)
    if
        type ~= CATEGORIES.player and
        type ~= CATEGORIES.enemy and
        type ~= CATEGORIES.neutral
    then
        error("Wrong type of category. Got: ", type)
        return
    end
    fixture:setCategory(type)
    fixture:setMask(type + 1)
end

function CategoryManager.setBulletproof(fixture)
    fixture:setCategory(CATEGORIES.bulletproof)
    fixture:setMask(CATEGORIES.player_bullets, CATEGORIES.enemy_bullets, CATEGORIES.neutral_bullets)
end

return CategoryManager