---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 16.10.2022 16:43
---

local tiny = require("libs/tiny")

local GraphicsSystem = tiny.processingSystem()
GraphicsSystem.filter = tiny.requireAll("graphics", "body")

function GraphicsSystem:process(entity, dt)
    local animation, image = entity.graphics:current()
    animation:update(dt)
    animation:draw(image, entity.body:getX(), entity.body:getY())
end

return GraphicsSystem