---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 26.11.2022 23:25
---

local tiny = require("libs/tiny")
local dump = require("utility/dump")

local Timer = require("utility/timer")

-- The purpose of HPSystem is to look out for collisions and
local HealthSystem = tiny.processingSystem()
HealthSystem.filter = tiny.requireAll("health", "behavior")

function HealthSystem:onAdd(entity)
    fill_table(entity.health, {
        count = 0,
        change = 0,
        i_time = 0.5 -- invincibility
    })
    entity.health.i_timer = Timer(entity.health.i_time)
end

function HealthSystem:process(entity, dt)
    local behavior = entity.behavior
    local health = entity.health

    health.i_timer:update(dt)

    if health.i_timer.is_on then
        health.change = 0
        return -- If invincibility frames are on - no handle
    end

    if health.change and health.change ~= 0 then
        if health.change < 0 then
            health.i_timer:start()
        end
        if behavior then
            entity[behavior].messages:push({"hurt", health.change})
        end
        health.count = health.count + health.change
        health.change = 0
    end
    if health.count < 0 then
        if behavior then
            entity[behavior].messages:push({"die"})
        end
        health.count = 0
    end
end

return HealthSystem