---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 26.11.2022 23:25
---

local tiny = require("libs/tiny")
local dump = require("utility/dump")

-- The purpose of HPSystem is to look out for collisions and
local HealthSystem = tiny.processingSystem()
HealthSystem.filter = tiny.requireAll("health", "behavior")

function HealthSystem:process(entity, dt)
    local behavior = entity.behavior
    local health = entity.health
    if not behavior then
        return
    end

    if health.change then
        entity[behavior].messages:push({"hurt", health.change})
        health.count = health.count + health.change
    end
    if health.count < 0 then
        entity[behavior].messages:push({"die"})
    end
end

return HealthSystem