---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 16.10.2022 16:41
---

local Vector = require('utility/vector')
local tiny = require("libs/tiny")


local PlayerControlSystem = tiny.processingSystem()
PlayerControlSystem.filter = tiny.requireAll("player", "body", "graphics")

function PlayerControlSystem:process(entity, dt)
    local velocity = Vector:new()
    local type = "idle"
    if love.keyboard.isDown("up") then
        velocity = velocity + {0,-100}
        type = "move"
    end
    if love.keyboard.isDown("down") then
        velocity = velocity + {0,100}
        type = "move"
    end
    if love.keyboard.isDown("left") then
        velocity = velocity + {-100,0}
        type = "move"
    end
    if love.keyboard.isDown("right") then
        velocity = velocity + {100,0}
        type = "move"
    end
    entity.body:setLinearVelocity(velocity:x(), velocity:y())
    entity.graphics:set(type)
end

return PlayerControlSystem