---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 16.10.2022 16:41
---

local Vector2, Vector3 = unpack(require('utility/vector'))
local tiny = require("libs/tiny")


local PlayerControlSystem = tiny.processingSystem()
PlayerControlSystem.filter = tiny.requireAll("player", "body", "sprite", "depth")

function PlayerControlSystem:process(entity, dt)
    local velocity = Vector2()
    local type = "idle"
    local depth = entity.depth.z
    if love.keyboard.isDown("up") then
        velocity = velocity + {0,-100}
        type = "move"
    end
    if love.keyboard.isDown("down") then
        velocity = velocity + {0,100}
        type = "move"
    end
    if love.keyboard.isDown("left") then
        velocity = velocity + {-100,0}
        type = "move"
    end
    if love.keyboard.isDown("right") then
        velocity = velocity + {100,0}
        type = "move"
    end
    if love.keyboard.isDown("q") then
        depth = depth / 0.95
    end
    if love.keyboard.isDown("e") then
        depth = depth * 0.95
    end

    entity.body:setLinearVelocity(velocity:x(), velocity:y())
    entity.sprite:set(type)
    entity.depth.z = depth
end

return PlayerControlSystem