---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 13.11.2022 1:13
---

local class = require("libs/30log")

local Scene = class("Scene", {
    load = function()  end,
    update = function(dt)  end,
    draw = function(dt)  end
})

return Scene