---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Meevere.
--- DateTime: 16.10.2022 16:45
---

local tiny = require("libs/tiny")

local PlayerControlSystem = require("src/PlayerSystem")
local SpriteSystem = require("src/SpriteSystem")

local world = tiny.world()
world:addSystem(PlayerControlSystem)
world:addSystem(SpriteSystem)

return world